// <auto-generated />
using System;
using LabBancoDeDados.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabBancoDeDados.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabBancoDeDados.Models.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("ARTISTA");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("MUSICA");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.MusicaPlaylist", b =>
                {
                    b.Property<int>("MusicaId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("OrdemNaPlaylist")
                        .HasColumnType("integer");

                    b.HasKey("MusicaId", "PlaylistId", "UsuarioId");

                    b.HasIndex("PlaylistId", "UsuarioId");

                    b.ToTable("MUSICA_PLAYLIST");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PlaylistId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PLAYLIST");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Musica", b =>
                {
                    b.HasOne("LabBancoDeDados.Models.Artista", "Artista")
                        .WithMany("Musicas")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.MusicaPlaylist", b =>
                {
                    b.HasOne("LabBancoDeDados.Models.Musica", "Musica")
                        .WithMany("MusicaPlaylists")
                        .HasForeignKey("MusicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabBancoDeDados.Models.Playlist", "Playlist")
                        .WithMany("MusicaPlaylists")
                        .HasForeignKey("PlaylistId", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musica");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Playlist", b =>
                {
                    b.HasOne("LabBancoDeDados.Models.Usuario", "Usuario")
                        .WithMany("Playlists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Artista", b =>
                {
                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Musica", b =>
                {
                    b.Navigation("MusicaPlaylists");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Playlist", b =>
                {
                    b.Navigation("MusicaPlaylists");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Usuario", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
