// <auto-generated />
using System;
using LabBancoDeDados.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabBancoDeDados.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabBancoDeDados.Models.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("ARTISTA");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nacionalidade = "Britânica",
                            Nome = "Queen"
                        },
                        new
                        {
                            Id = 2,
                            Nacionalidade = "Britânica",
                            Nome = "Led Zeppelin"
                        },
                        new
                        {
                            Id = 3,
                            Nacionalidade = "Australiana",
                            Nome = "AC/DC"
                        },
                        new
                        {
                            Id = 4,
                            Nacionalidade = "Brasileira",
                            Nome = "Banda X (Pop)"
                        });
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("MUSICA");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistaId = 1,
                            DuracaoSegundos = 354,
                            Titulo = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = 2,
                            ArtistaId = 2,
                            DuracaoSegundos = 482,
                            Titulo = "Stairway to Heaven"
                        },
                        new
                        {
                            Id = 3,
                            ArtistaId = 3,
                            DuracaoSegundos = 255,
                            Titulo = "Back In Black"
                        },
                        new
                        {
                            Id = 4,
                            ArtistaId = 1,
                            DuracaoSegundos = 160,
                            Titulo = "We Will Rock You"
                        },
                        new
                        {
                            Id = 5,
                            ArtistaId = 4,
                            DuracaoSegundos = 180,
                            Titulo = "Musica Pop Brasileira"
                        },
                        new
                        {
                            Id = 6,
                            ArtistaId = 3,
                            DuracaoSegundos = 292,
                            Titulo = "Thunderstruck"
                        });
                });

            modelBuilder.Entity("LabBancoDeDados.Models.MusicaPlaylist", b =>
                {
                    b.Property<int>("MusicaId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("OrdemNaPlaylist")
                        .HasColumnType("integer");

                    b.HasKey("MusicaId", "PlaylistId", "UsuarioId");

                    b.HasIndex("PlaylistId", "UsuarioId");

                    b.ToTable("MUSICA_PLAYLIST");

                    b.HasData(
                        new
                        {
                            MusicaId = 1,
                            PlaylistId = 1,
                            UsuarioId = 1,
                            OrdemNaPlaylist = 1
                        },
                        new
                        {
                            MusicaId = 3,
                            PlaylistId = 1,
                            UsuarioId = 1,
                            OrdemNaPlaylist = 2
                        },
                        new
                        {
                            MusicaId = 4,
                            PlaylistId = 1,
                            UsuarioId = 1,
                            OrdemNaPlaylist = 3
                        },
                        new
                        {
                            MusicaId = 2,
                            PlaylistId = 2,
                            UsuarioId = 2,
                            OrdemNaPlaylist = 1
                        },
                        new
                        {
                            MusicaId = 3,
                            PlaylistId = 3,
                            UsuarioId = 1,
                            OrdemNaPlaylist = 1
                        },
                        new
                        {
                            MusicaId = 6,
                            PlaylistId = 3,
                            UsuarioId = 1,
                            OrdemNaPlaylist = 2
                        });
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PlaylistId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PLAYLIST");

                    b.HasData(
                        new
                        {
                            PlaylistId = 1,
                            UsuarioId = 1,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Rock do Pablo"
                        },
                        new
                        {
                            PlaylistId = 2,
                            UsuarioId = 2,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Baladas do Josue"
                        },
                        new
                        {
                            PlaylistId = 3,
                            UsuarioId = 1,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Heavy Riffs"
                        });
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("USUARIO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "pablo@aluno.com",
                            Username = "Pablo"
                        },
                        new
                        {
                            Id = 2,
                            Email = "josue@aluno.com",
                            Username = "Josue"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alexandre@aluno.com",
                            Username = "Alexandre"
                        });
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Musica", b =>
                {
                    b.HasOne("LabBancoDeDados.Models.Artista", "Artista")
                        .WithMany("Musicas")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.MusicaPlaylist", b =>
                {
                    b.HasOne("LabBancoDeDados.Models.Musica", "Musica")
                        .WithMany("MusicaPlaylists")
                        .HasForeignKey("MusicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabBancoDeDados.Models.Playlist", "Playlist")
                        .WithMany("MusicaPlaylists")
                        .HasForeignKey("PlaylistId", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musica");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Playlist", b =>
                {
                    b.HasOne("LabBancoDeDados.Models.Usuario", "Usuario")
                        .WithMany("Playlists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Artista", b =>
                {
                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Musica", b =>
                {
                    b.Navigation("MusicaPlaylists");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Playlist", b =>
                {
                    b.Navigation("MusicaPlaylists");
                });

            modelBuilder.Entity("LabBancoDeDados.Models.Usuario", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
